# Generated by Django 4.2.8 on 2024-01-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appgestaoimoveis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratos",
            name="data_base",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contratos",
            name="valor_aluguel",
            field=models.CharField(max_length=255),
        ),
    ]
