# Generated by Django 4.2.8 on 2024-01-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appgestaoimoveis", "0002_alter_contratos_data_base_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contratos",
            name="inquilino",
        ),
        migrations.AddField(
            model_name="contratos",
            name="nome",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="appgestaoimoveis.inquilinos",
            ),
            preserve_default=False,
        ),
    ]
