# Generated by Django 4.2.8 on 2024-01-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appgestaoimoveis", "0004_remove_contratos_cidade_alter_contratos_endereco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratos",
            name="valor_aluguel",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
