# Generated by Django 4.2.8 on 2024-01-08 21:00

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ("appgestaoimoveis", "0005_alter_contratos_valor_aluguel"),
    ]

    
