# Generated by Django 4.2.8 on 2024-01-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appgestaoimoveis", "0011_alter_contratos_data_base"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratos",
            name="data_base",
            field=models.CharField(max_length=50),
        ),
    ]
