# Generated by Django 4.2.8 on 2024-01-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appgestaoimoveis", "0012_alter_contratos_data_base"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratos",
            name="data_base",
            field=models.DateField(blank=True, null=True, verbose_name="data"),
        ),
    ]
