# Generated by Django 4.2.8 on 2024-01-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appgestaoimoveis", "0014_alter_contratos_data_base"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquilinos",
            name="documento_tipo",
            field=models.CharField(
                choices=[("CPF", "CPF"), ("CNPJ", "CNPJ")], default=1, max_length=4
            ),
            preserve_default=False,
        ),
    ]
