# Generated by Django 4.2.8 on 2024-01-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appgestaoimoveis", "0015_inquilinos_documento_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquilinos",
            name="telefone",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
